### ISSUE TITLE
Assigned Keyboard shortcut to `Open in Application`, But creates errors.

### ISSUE THREAD

**Issue by anishmittal2020** [fabiospampinato/vscode-open-in-application#7]
Assigned Keyboard shortcut to `Open in Application`. But I get this error `For this file you'll have to trigger this action from the right-click menu` when I try to open a pdf file in system application.

**Comment by fabiospampinato** [comment]
There's no API for retrieving the path of open binary files, so for those situations you should right-click the tab and perform the action from there.

**Comment by macromaniac** [comment]
I want to add that you can still use keyboard shortcuts here to open the file. Since "Open in Application" is at the top (hopefully always), you can open whatever file you have with the following hotkey combo (assuming the file is open in your editor, e.g. select the file with ctrl p):

Ctrl+Shift+e - Focus explorer window
Right click - (your keyboard needs to have a key for right click)
Down - go down in the context menu
Enter - select this context menu item

Once you get good at the combo you can do this pretty quick
